// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: api/saas-backend/v1/services/backend.service.v1.proto

package servicev1

import (
	context "context"
	resources "github.com/go-micro-saas/saas-backend/api/saas-backend/v1/resources"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SrvSaasBackendV1_Ping_FullMethodName = "/saas.api.backend.servicev1.SrvSaasBackendV1/Ping"
)

// SrvSaasBackendV1Client is the client API for SrvSaasBackendV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SrvSaasBackendV1 ...
type SrvSaasBackendV1Client interface {
	// Ping ping
	Ping(ctx context.Context, in *resources.PingReq, opts ...grpc.CallOption) (*resources.PingResp, error)
}

type srvSaasBackendV1Client struct {
	cc grpc.ClientConnInterface
}

func NewSrvSaasBackendV1Client(cc grpc.ClientConnInterface) SrvSaasBackendV1Client {
	return &srvSaasBackendV1Client{cc}
}

func (c *srvSaasBackendV1Client) Ping(ctx context.Context, in *resources.PingReq, opts ...grpc.CallOption) (*resources.PingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(resources.PingResp)
	err := c.cc.Invoke(ctx, SrvSaasBackendV1_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SrvSaasBackendV1Server is the server API for SrvSaasBackendV1 service.
// All implementations must embed UnimplementedSrvSaasBackendV1Server
// for forward compatibility.
//
// SrvSaasBackendV1 ...
type SrvSaasBackendV1Server interface {
	// Ping ping
	Ping(context.Context, *resources.PingReq) (*resources.PingResp, error)
	mustEmbedUnimplementedSrvSaasBackendV1Server()
}

// UnimplementedSrvSaasBackendV1Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSrvSaasBackendV1Server struct{}

func (UnimplementedSrvSaasBackendV1Server) Ping(context.Context, *resources.PingReq) (*resources.PingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedSrvSaasBackendV1Server) mustEmbedUnimplementedSrvSaasBackendV1Server() {}
func (UnimplementedSrvSaasBackendV1Server) testEmbeddedByValue()                          {}

// UnsafeSrvSaasBackendV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SrvSaasBackendV1Server will
// result in compilation errors.
type UnsafeSrvSaasBackendV1Server interface {
	mustEmbedUnimplementedSrvSaasBackendV1Server()
}

func RegisterSrvSaasBackendV1Server(s grpc.ServiceRegistrar, srv SrvSaasBackendV1Server) {
	// If the following call pancis, it indicates UnimplementedSrvSaasBackendV1Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SrvSaasBackendV1_ServiceDesc, srv)
}

func _SrvSaasBackendV1_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrvSaasBackendV1Server).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SrvSaasBackendV1_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrvSaasBackendV1Server).Ping(ctx, req.(*resources.PingReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SrvSaasBackendV1_ServiceDesc is the grpc.ServiceDesc for SrvSaasBackendV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SrvSaasBackendV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "saas.api.backend.servicev1.SrvSaasBackendV1",
	HandlerType: (*SrvSaasBackendV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _SrvSaasBackendV1_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/saas-backend/v1/services/backend.service.v1.proto",
}
