// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package serviceexporter

import (
	"github.com/go-kratos/kratos/v2/transport/grpc"
	"github.com/go-kratos/kratos/v2/transport/http"
	"github.com/go-micro-saas/account-service/app/account-service/internal/biz/biz"
	"github.com/go-micro-saas/account-service/app/account-service/internal/biz/event"
	"github.com/go-micro-saas/account-service/app/account-service/internal/conf"
	"github.com/go-micro-saas/account-service/app/account-service/internal/data/cache"
	"github.com/go-micro-saas/account-service/app/account-service/internal/data/data"
	"github.com/go-micro-saas/account-service/app/account-service/internal/service/dto"
	"github.com/go-micro-saas/account-service/app/account-service/internal/service/service"
	"github.com/go-micro-saas/service-api/app/snowflake-service"
	"github.com/ikaiguang/go-srv-kit/service/cleanup"
	"github.com/ikaiguang/go-srv-kit/service/setup"
)

// Injectors from wire.go:

func exportServices(launcherManager setuputil.LauncherManager, hs *http.Server, gs *grpc.Server) (cleanuputil.CleanupManager, func(), error) {
	logger, err := setuputil.GetLogger(launcherManager)
	if err != nil {
		return nil, nil, err
	}
	authRepo, err := setuputil.GetAuthManager(launcherManager)
	if err != nil {
		return nil, nil, err
	}
	serviceAPIManager, err := setuputil.GetServiceAPIManager(launcherManager)
	if err != nil {
		return nil, nil, err
	}
	serviceConfig := conf.GetServiceConfig()
	getNodeIdReq, err := dto.ToPbGetNodeIdReq(serviceConfig)
	if err != nil {
		return nil, nil, err
	}
	v := dto.GetNodeIDOptions(logger, serviceConfig)
	snowflake, cleanup, err := snowflakeapi.GetSingletonIDGeneratorByHTTPAPI(serviceAPIManager, getNodeIdReq, v...)
	if err != nil {
		return nil, nil, err
	}
	bootstrap := setuputil.GetConfig(launcherManager)
	verifyCodeConfig := dto.ToBoVerifyCodeConfig(bootstrap)
	db, err := setuputil.GetRecommendDBConn(launcherManager)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userDataRepo := data.NewUserDataRepo(logger, db)
	userRegEmailDataRepo := data.NewUserRegEmailDataRepo(logger, db)
	userRegPhoneDataRepo := data.NewUserRegPhoneDataRepo(logger, db)
	userVerifyCodeDataRepo := data.NewUserVerifyCodeRepo(db)
	universalClient, err := setuputil.GetRedisClient(launcherManager)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	verifyCodeCacheRepo := caches.NewVerifyCodeCache(logger, universalClient)
	userAuthBizRepo := biz.NewUserAuthBiz(logger, authRepo, snowflake, verifyCodeConfig, userDataRepo, userRegEmailDataRepo, userRegPhoneDataRepo, userVerifyCodeDataRepo, verifyCodeCacheRepo)
	connectionWrapper, err := setuputil.GetRabbitmqConn(launcherManager)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userEventHistoryRepo := data.NewUserEventHistoryRepo(logger, db)
	sendEmailCodeEventRepo := events.NewSendEmailCodeEventRepo(logger, connectionWrapper, userEventHistoryRepo)
	srvUserAuthV1Server := service.NewUserAuthService(logger, userAuthBizRepo, sendEmailCodeEventRepo)
	userBizRepo := biz.NewAccountBiz(logger, snowflake, userDataRepo, userRegEmailDataRepo, userRegPhoneDataRepo, userVerifyCodeDataRepo)
	srvAccountV1Server := service.NewAccountService(logger, userBizRepo)
	sendEmailCodeConfig, err := dto.ToBoSendEmailCodeConfig(serviceConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	sendEmailCodeBizRepo, cleanup2, err := biz.NewSendEmailCodeBiz(logger, sendEmailCodeConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	srvAccountEventV1Server := service.NewAccountEventService(logger, sendEmailCodeBizRepo, sendEmailCodeEventRepo)
	cleanupManager, err := service.RegisterServices(hs, gs, srvUserAuthV1Server, srvAccountV1Server, srvAccountEventV1Server)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return cleanupManager, func() {
		cleanup2()
		cleanup()
	}, nil
}
