version: '3'

services:
  dev-saas-backend:
    image: saas-backend:latest
    container_name: dev-saas-backend
    ports:
      - "10701:10701"
      - "10702:10702"
    networks:
      - my-network
    volumes:
      - dev_saas_backend_data:/myworkspace/golang/src/workspace/runtime
      - ./configs:/myworkspace/golang/src/workspace/configs
    environment:
      TZ: Asia/Shanghai
    #entrypoint: ["/bin/bash"]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:10701/api/v1/saas-backend/ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped

networks:
  my-network: # 已有的网络的名称
    external: true  # 标记为外部网络，表示这是已存在的网络

volumes:
  dev_saas_backend_data:
    driver: local
